### ISSUE TITLE
How to use this module with mysql DB/Module

### ISSUE THREAD

**Issue by javabala** [expressjs/express-paginate#12]
Hi,

I am new to the express and node js. I don't know how to integrate this module with mysql module.

Can any one please guide me?

**Comment by niftylettuce** [comment]
Use `knex` package (or another package that lets you write SQL queries) from NPM and connect it to your MySQL server.

Then write a query using knex (or your alternative) to paginate some data from your DB.

```js
var start = (req.query.page - 1) * req.query.limit;
var end = (req.query.page * req.query.limit) - 1;
var query = 'SELECT * FROM some_table_name LIMIT ' + start + ',' + end;
```

(there are more efficient ways to write this SQL query, but this is just a simple example)

You just hook in the `express-paginate` middleware, then write normal SQL queries, and for your limit and offset numbers use the provided `req.query.limit` and `req.query.page` values (see the Readme).

Does this help @javabala?

**Comment by wzup** [comment]
@niftylettuce 

Are you sure you wrote correct example?
`end` is actually a limit and it is normally a fixed value. Like only 10, 15, 20, so on records. So
```
LIMIT 20, 10
```
actually means: I need just 10 records from 20th.

And in your example `end` is not a fixed value. It is increased with every page.

If your limit is to return just 10 records every time, then by your example you get this:
```
LIMIT 0, 9 // returns 9 records
LIMIT 10, 19 // returns 19 records
LIMIT 20, 29 // returns 29 records
```

**Comment by niftylettuce** [comment]
@wzup can you rewrite this and add example to README?
