### ISSUE TITLE
Display group button of pages

### ISSUE THREAD

**Issue by khanghoang** [expressjs/express-paginate#14]
Hi,
I think this is very convenient view helper. But in my case, I wanna have group button of pages like image below:

![petronas contest 2015-10-29 12-35-52](https://cloud.githubusercontent.com/assets/3213579/10810997/a5b0b190-7e39-11e5-9cca-fb00a2142640.png)

I think it makes sense when you deal with data table in CMS

**Comment by niftylettuce** [comment]
Nice, just accepted your pull request.  Publishing new version now to NPM.
