### ISSUE TITLE
Example with EJS

### ISSUE THREAD

**Issue by jpacora** [expressjs/express-paginate#20]
Hello, I'm trying to port the Jade example to EJS with no result, help me please!

**Comment by ultimate-tester** [comment]
This is how I implemented it:

```
<a href="<%= paginate.href(true) %>">Prev</a>

<% for(var i = 0; i < pages.length;i++) { %>
<% var page = pages[i]; %>
<a href="<%= page.url %>" class="<%= paginate.page == page.number ? 'active' : ''%>"><%= page.number %></a>
<% } %>

<a href="<%= paginate.href() %>">Next</a>
```

**Comment by niftylettuce** [comment]
@ultimate-tester can you submit a PR to the Readme with this example you crafted?

**Comment by ramanieto** [comment]
I know this is old, but I thought it might help other people. Let me know if you would like me to submit PR to the Readme.

`<% if (paginate.hasPreviousPages || paginate.hasNextPages(pageCount) ) { %>
  <div class="navigation well-sm" id="pagination">
    <ul class="pager">
      <% if (paginate.hasPreviousPages) { %>
        <li class="previous">
          <a href="<%= paginate.href(true) %>">
            <i class="fa fa-arrow-circle-left"></i>
            Previous
          </a>  
        </li>
      <% } %>  
      <% if (pages) { %>
        <% pages.forEach(function(page, i){ %>
          <a class="btn btn-default" href="<%= page.url %>"><%= page.number %></a>
        <% }); %>
      <% } %>  
      <% if (paginate.hasNextPages(pageCount)) { %>
        <li class="next">
          <a href="<%= paginate.href() %>">
            Next &nbsp;
            <i class="fa fa-arrow-circle-right"></i>
          </a>  
        </li>
      <% } %>  
      </ul>      
    </div>
  <% } %>`

**Comment by TenzenIga** [comment]
@ultimate-tester 
Nice. 
What about sorting. Is there is a way to port it to ejs?

**Comment by niftylettuce** [comment]
Great - please submit PR @ultimate-tester , tyvm!

**Comment by ultimate-tester** [comment]
I'll create a PR later (in 2 weeks), am on holiday now ;)

**Comment by yogeshfgiet** [comment]
Great it working for me !

**Comment by niftylettuce** [comment]
PR welcome
