### ISSUE TITLE
Something wrong with paginate.getArrayPages

### ISSUE THREAD

**Issue by IchiNiNiIchi** [expressjs/express-paginate#26]
When I exec the following code in my express demo

```
var pages = paginate.getArrayPages(req)(3, 2, 2);
pages.forEach(function(page) {
    console.log(page);
});
```

I get the following ouput

```
 { number: 0, url: '/products?page=0&limit=10' }
 { number: 1, url: '/products?page=1&limit=10' }
 { number: 2, url: '/products?page=2&limit=10' }
```

**Comment by niftylettuce** [comment]
@IchiNiNiIchi does this resolve your issue? <http://stackoverflow.com/questions/39676397/error-express-paginate-limit-is-not-a-number-0>

**Comment by niftylettuce** [comment]
@IchiNiNiIchi does this resolve your issue? <http://stackoverflow.com/a/39689389>

**Comment by IchiNiNiIchi** [comment]
@niftylettuce thank you for your reply. My question is the result include a "page 0" when I call paginate.getArrayPages(3, 2, 2). Finally I get around this by changing
` var start = (currentPage < (limit - 1)) ? 1 : (end - limit) + 1;`
to
` var start = (currentPage <= (limit - 1)) ? 1 : (end - limit) + 1;`
in https://github.com/expressjs/express-paginate/blob/a34a719fcc308bd8d82b46a9d51dc3bf05faae09/index.js#L72
but I don't know does the change works for other input.

**Comment by rajivnarayana** [comment]
This is still an issue. Changing the code in local copy cannot be a solution. Please reopen this bug.

@niftylettuce , SO Link does not fix anything.

**Comment by niftylettuce** [comment]
@rajivnarayana I reopened the issue - just saw this now

**Comment by niftylettuce** [comment]
feel free to submit a PR!  I don't use Express anymore - would you like to help maintain?

**Comment by rajivnarayana** [comment]
Will give this a try and submit a PR. It will fix an outstanding bug in one of our projects.

Would like to maintain this plugin!

**Comment by niftylettuce** [comment]
Great @rajivnarayana!  Added you as a collaborator.  Once your code is in ping me and I will release a new version.  When I'm comfortable I'll add you as an NPM owner!

**Comment by rajivnarayana** [comment]
Thanks @niftylettuce for merging v0.3.0. This issue should now be fixed and could be closed.
