### ISSUE TITLE
How to send "skip" parameter?

### ISSUE THREAD

**Issue by piavgh** [expressjs/express-paginate#45]
Hi everyone,

In your example, I see this code limit(req.query.limit).skip(req.skip).lean().exec(),

About the "limit" parameter, I can send it from client without problem (I'm using Axios)

But for the "skip" parameter, I don't know how to send that value? Because it doesn't belong to req.query, req.params or req.body.

How can I send the value for "skip"?

Thanks.

**Comment by niftylettuce** [comment]
Skip is automatically set for you! https://github.com/expressjs/express-paginate/blob/master/index.js#L111

**Comment by piavgh** [comment]
Thanks @niftylettuce ,

Turn out that it has req.query.page :D
