### ISSUE TITLE
RethinkDB

### ISSUE THREAD

**Issue by DetectiveHuman** [expressjs/express-paginate#47]
Hello,

Is there an example of how to use this with RethinkDB?

Any tutorial would be greatly appreciated.

**Comment by niftylettuce** [comment]
I don't use RethinkDB but you could probably find the answer from Google:

Try these queries:

> "rethinkdb nodejs"
> "rethinkdb nodejs pagination"
> "rethinkdb pagination"

You'd implement `req.query.limit` and `req.skip` for page limit and offset/skip respectively

Maybe this is a start https://stackoverflow.com/questions/34729763/rethinkdb-pagination-using-slice-or-limit-skip-with-changes

**Comment by DetectiveHuman** [comment]
Tried it, nothing seems to work..
