### ISSUE TITLE
how to set first and last link?

### ISSUE THREAD

**Issue by coaperator** [expressjs/express-paginate#48]
page.url - current link
paginate.href(true) - prev link
paginate.href() - next link

How to add the first and last link, if I, for example, on page 50?

And the second question - how to disable the parameter limit in the URL?

**Comment by leviwheatcroft** [comment]
It looks like `paginate.href` [returns a query string with whatever params you throw at it](https://github.com/expressjs/express-paginate/blob/master/index.js#L42).

So link for first page is:

`href=paginate.href({ page: 1})`

And link for last page is

`paginate.href({ page: pageCount })`

but you need to set `pageCount` yourself as shown in the example in the readme.

**Comment by zbubric** [comment]
And, if someone bump into this issue again, I'll just leave it here:

// req is express request object
// pageCount is total number of pages, you need to calculate it on your own

paginate.href(req)(false, {page: 1}),
paginate.href(req)(false, {page: pageCount}),

Solution provided above has cause errors on:
express: 4.17.1
express-paginate: 1.0.2
