### ISSUE TITLE
Handlebars paginate.href true gives weird value

### ISSUE THREAD

**Issue by JurajJakubov** [expressjs/express-paginate#49]
Hello i am trying to make previous button in handlebars
`<a href="{{paginate.href true}}" class="paginator-itemLink">Prev</a>`
Well it works it goes back but url looks like this
`http://localhost:3000/users/show?page=3&limit=5&name=paginate.href&data%5Bexphbs%5D%5Bcache%5D=false&data%5Bexphbs%5D%5Bview%5D=..%5Cmodules%5Cusers%5Cviews%5CuserList&data%5Bexphbs%5D%5Blayout%5D=cmsLayout&data%5Bexphbs%5D%5BfilePath%5D=C%3A%5CUsers%5CJuraj%20Jakubov%5CPraca%5CWebov%C3%A9%20aplik%C3%A1cie%5CNodeCMS%5Cmodules%5Cusers%5Cviews%5CuserList.handlebars&data%5B_parent%5D%5Bexphbs%5D%5Bcache%5D=false&data%5B_parent%5D%5Bexphbs%5D%5Bview%5D=..%5Cmodules%5Cusers%5Cviews%5CuserList&data%5B_parent%5D%5Bexphbs%5D%5Blayout%5D=cmsLayout&data%5B_parent%5D%5Bexphbs%5D%5BfilePath%5D=C%3A%5CUsers%5CJuraj%20Jakubov%5CPraca%5CWebov%C3%A9%20aplik%C3%A1cie%5CNodeCMS%5Cmodules%5Cusers%5Cviews%5CuserList.handlebars&data%5Broot%5D%5Bsettings%5D%5Bx-powered-by%5D=true&data%5Broot%5D%5Bsettings%5D%5Betag%5D=weak&data%5Broot%5D%5Bsettings%5D%5Benv%5D=development&data%5Broot%5D%5Bsettings%5D%5Bquery%20parser%5D=extended&data%5Broot%5D%5Bsettings%5D%5Bsubdomain%20offset%5D=2&data%5Broot%5D%5Bsettings%5D%5Bviews%5D=C%3A%5CUsers%5CJuraj%20Jakubov%5CPraca%5CWebov%C3%A9%20aplik%C3%A1cie%5CNodeCMS%5Cviews&data%5Broot%5D%5Bsettings%5D%5Bjsonp%20callback%20name%5D=callback&data%5Broot%5D%5Buser%5D=&data%5Broot%5D%5BcsrfToken%5D=NDvvfCUK-51L1-xOQagieUfzN3nNSJTLR5mc&data%5Broot%5D%5Bpaginate%5D%5Bpage%5D=4&data%5Broot%5D%5Bpaginate%5D%5Blimit%5D=5&data%5Broot%5D%5Bpaginate%5D%5BhasPreviousPages%5D=true&data%5Broot%5D%5Blayout%5D=cmsLayout&data%5Broot%5D%5Busers%5D%5B0%5D%5B_id%5D%5B_bsontype%5D=ObjectID&data%5Broot%5D%5Busers%5D%5B0%5D%5B_id%5D%5Bid%5D=%5C%029%EF%BF%BD%2B%EF%BF%BD%EF%BF%BD%40Dv%3C%EF%BF%BD&data%5Broot%5D%5Busers%5D%5B0%5D%5Bfirstname%5D=xxxxxxxxxfsdf&data%5Broot%5D%5Busers%5D%5B0%5D%5Blastname%5D=6j2gh6jhgdfdsfgfgdggfddffdfdghgfxxxxxxxxxfsdf&data%5Broot%5D%5Busers%5D%5B0%5D%5Bemail%5D=xxxxxxxxxfsdf%40xxxxxxxxxfsdf.com&data%5Broot%5D%5Busers%5D%5B0%5D%5Bpassword%5D=%242a%2410%24ktxWt.LVWrlcn2OTNK7w0.gv7cgKAxrTkAvqEUYAyRZqhPO4Rr196&data%5Broot%5D%5Busers%5D%5B0%5D%5Bipadress%5D=%3A%3A1&data%5Broot%5D%5Busers%5D%5B0%5D%5Bcreated%5D=2018-12-01T07%3A34%3A45.718Z&data%5Broot%5D%5Busers%5D%5B0%5D%5Bprovider%5D=local&data%5Broot%5D%5Busers%5D%5B0%5D%5Bstatus%5D=0&data%5Broot%5D%5Busers%5D%5B0%5D%5BsecretToken%5D=QnEDBzliiEGA4Aj5VXXkarIWIgaHy0Hk&data%5Broot%5D%5Busers%5D%5B0%5D%5B__v%5D=0&data%5Broot%5D%5Busers%5D%5B1%5D%5B_id%5D%5B_bsontype%5D=ObjectID&data%5Broot%5D%5Busers%5D%5B1%5D%5B_id%5D%5Bid%5D=%5C%029%EF%BF%BD%2B%EF%BF%BD%EF%BF%BD%40Dv%3C%EF%BF%BD&data%5Broot%5D%5Busers%5D%5B1%5D%5Bfirstname%5D=xxxxxxxxxfsdffsd&data%5Broot%5D%5Busers%5D%5B1%5D%5Blastname%5D=6j2gh6jhgdfdsfgfsdffgdggfddffdfdghgfxxxfsdxxxxxxfsdf&data%5Broot%5D%5Busers%5D%5B1%5D%5Bemail%5D=xxxxxxxfdsxxfsdf%40xxxxxfsdxxxxfsdf.com&data%5Broot%5D%5Busers%5D%5B1%5D%5Bpassword%5D=%242a%2410%24vB%2FOUFuqOcGKg7DOmxraJO7SzCm54vn.jkKbc3cMSKyrCBNfkUuIm&data%5Broot%5D%5Busers%5D%5B1%5D%5Bipadress%5D=%3A%3A1&data%5Broot%5D%5Busers%5D%5B1%5D%5Bcreated%5D=2018-12-01T07%3A34%3A51.523Z&data%5Broot%5D%5Busers%5D%5B1%5D%5Bprovider%5D=local&data%5Broot%5D%5Busers%5D%5B1%5D%5Bstatus%5D=0&data%5Broot%5D%5Busers%5D%5B1%5D%5BsecretToken%5D=i4ZcErC8PMLvQIq0uTsRWVnqxObPFKMQ&data%5Broot%5D%5Busers%5D%5B1%5D%5B__v%5D=0&data%5Broot%5D%5Busers%5D%5B2%5D%5B_id%5D%5B_bsontype%5D=ObjectID&data%5Broot%5D%5Busers%5D%5B2%5D%5B_id%5D%5Bid%5D=%5C%029%EF%BF%BD%2B%EF%BF%BD%EF%BF%BD%40Dv%3C%EF%BF%BD&data%5Broot%5D%5Busers%5D%5B2%5D%5Bfirstname%5D=xxxxxxxxxfsdffsdf&data%5Broot%5D%5Busers%5D%5B2%5D%5Blastname%5D=6j2gh6jhgdfdsfgfsdffgdggfddffdfdghgfxxfxfsdxxxxxxfsdf&data%5Broot%5D%5Busers%5D%5B2%5D%5Bemail%5D=xxxxxxxfdfsxxfsdf%40xxxxxfsdxxxxfsdf.com&data%5Broot%5D%5Busers%5D%5B2%5D%5Bpassword%5D=%242a%2410%24VdE04Mft6TFPXVhoTjHXJOr57VxnFD5tiv5lsf64irSVNqQXm7YRG&data%5Broot%5D%5Busers%5D%5B2%5D%5Bipadress%5D=%3A%3A1&data%5Broot%5D%5Busers%5D%5B2%5D%5Bcreated%5D=2018-12-01T07%3A36%3A18.200Z&data%5Broot%5D%5Busers%5D%5B2%5D%5Bprovider%5D=local&data%5Broot%5D%5Busers%5D%5B2%5D%5Bstatus%5D=0&data%5Broot%5D%5Busers%5D%5B2%5D%5BsecretToken%5D=8pzb0rjCpqSpg3jQek04NRL8cXE3b7sm&data%5Broot%5D%5Busers%5D%5B2%5D%5B__v%5D=0&data%5Broot%5D%5Busers%5D%5B3%5D%5B_id%5D%5B_bsontype%5D=ObjectID&data%5Broot%5D%5Busers%5D%5B3%5D%5B_id%5D%5Bid%5D=%5C%029%EF%BF%BD%2B%EF%BF%BD%EF%BF%BD%40Dv%3C%EF%BF%BD&data%5Broot%5D%5Busers%5D%5B3%5D%5Bfirstname%5D=xxxxxxgfdxxxfsdffsdf&data%5Broot%5D%5Busers%5D%5B3%5D%5Blastname%5D=6j2gh6jhgdfdsfgfsgdfdffgdggfddffdfdghgfxxfxfsdxxxxxxfsdf&data%5Broot%5D%5Busers%5D%5B3%5D%5Bemail%5D=xxxxxxxfdfgfdsxxfsdf%40xxxxxfgfddxxxxfsdf.com&data%5Broot%5D%5Busers%5D%5B3%5D%5Bpassword%5D=%242a%2410%24o3xpsEpYKoqivpOS9Pbqr.j.EXJHPn3sC8yFtqFfien9nYATI6VWm&data%5Broot%5D%5Busers%5D%5B3%5D%5Bipadress%5D=%3A%3A1&data%5Broot%5D%5Busers%5D%5B3%5D%5Bcreated%5D=2018-12-01T07%3A36%3A24.054Z&data%5Broot%5D%5Busers%5D%5B3%5D%5Bprovider%5D=local&data%5Broot%5D%5Busers%5D%5B3%5D%5Bstatus%5D=0&data%5Broot%5D%5Busers%5D%5B3%5D%5BsecretToken%5D=VOv4bEblVtZQK1kUHaYqvKR1T4xryr6u&data%5Broot%5D%5Busers%5D%5B3%5D%5B__v%5D=0&data%5Broot%5D%5BpageCount%5D=4&data%5Broot%5D%5BitemCount%5D=19&data%5Broot%5D%5Bhas_prev%5D=true&data%5Broot%5D%5Bhas_next%5D=false&data%5Broot%5D%5Bpages%5D%5B0%5D%5Bnumber%5D=2&data%5Broot%5D%5Bpages%5D%5B0%5D%5Burl%5D=%2Fusers%2Fshow%3Fpage%3D2%26limit%3D5&data%5Broot%5D%5Bpages%5D%5B1%5D%5Bnumber%5D=3&data%5Broot%5D%5Bpages%5D%5B1%5D%5Burl%5D=%2Fusers%2Fshow%3Fpage%3D3%26limit%3D5&data%5Broot%5D%5Bpages%5D%5B2%5D%5Bnumber%5D=4&data%5Broot%5D%5Bpages%5D%5B2%5D%5Burl%5D=%2Fusers%2Fshow%3Fpage%3D4%26limit%3D5&data%5Broot%5D%5B_locals%5D%5Buser%5D=&data%5Broot%5D%5B_locals%5D%5BcsrfToken%5D=NDvvfCUK-51L1-xOQagieUfzN3nNSJTLR5mc&data%5Broot%5D%5B_locals%5D%5Bpaginate%5D%5Bpage%5D=4&data%5Broot%5D%5B_locals%5D%5Bpaginate%5D%5Blimit%5D=5&data%5Broot%5D%5B_locals%5D%5Bpaginate%5D%5BhasPreviousPages%5D=true&data%5Broot%5D%5Bcache%5D=false`

**Comment by niftylettuce** [comment]
PR welcome if it is a bug
