### ISSUE TITLE
@expressjs/triagers lack ability to add labels in express-paginate 

### ISSUE THREAD

**Issue by mastermatt** [expressjs/express-paginate#55]
The team appears to only have **Read** instead of **Triage** permission level.

**Comment by jonchurch** [comment]
@dougwilson @wesleytodd I can't add repos to the team permissions, but someone with admin perms can go here to do it https://github.com/orgs/expressjs/teams/triagers/repositories

**Comment by dougwilson** [comment]
This repo falls outside of the Express TC, hence why the permissions are missing.
