### ISSUE TITLE
Different limits for multiple resources

### ISSUE THREAD

**Issue by zebapy** [expressjs/express-paginate#9]
I have two different resources and I want to control the limit for each one. 

Resource 1 needs a limit of 9, and resource 2 needs a 25 limit. How can I achieve this? Seems the middleware sets the same limit for each. 

I have tried:

`app.use('/resource1', paginate.middleware(9, 18))`
`app.use('/resource2', paginate.middleware(25, 100))`

But this doesn't work as you may imagine.

**Comment by B3rn475** [comment]
I think that this will solve your problem
https://github.com/expressjs/express-paginate/pull/10

**Comment by zebapy** [comment]
This is perfect.

**Comment by zebapy** [comment]
@niftylettuce would this be mergeable?

**Comment by niftylettuce** [comment]
Certainly.

**Comment by niftylettuce** [comment]
Merging now.
